# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10t9mAX6M-jcuLU-0F4n7XuXYZweqXl54
"""

#Este simbolo se utiliza para comentar el codigo.
print("Hola grupo 230 de la carrera tecnica de programacion")
#como consultar el tipo de dato
print( type("soy un dato str"))  #tipo ´str´
print(type(5)) # tipo ´int´
print(type(1.5)) # tipo ´float´
print (type(3+1j)) #tipo ´complex´
print(type(True)) # tipo bool
print(type("mi cadena de texto")) # tipo ´nonetype´